### ISSUE TITLE
Deploy via docker not work

### ISSUE THREAD

**Issue by k8scat** [crawlab-team/artipub#157]
![image](https://user-images.githubusercontent.com/55872984/113243448-9d59b480-92e5-11eb-880c-7b8fa1c3aef5.png)

**Comment by k8scat** [comment]
```yaml
version: "3.3"
services:
  app:
    image: "tanliyuan123/artipub:1.3.0"
    environment:
      MONGO_HOST: "mongo"
      # MONGO_USERNAME: root
      # MONGO_PASSWORD: example
      ARTIPUB_API_ADDRESS: "http://localhost:3000" # 后端API地址，如果安装地址不在本机，请修改为协议+服务器IP地址+端口号（默认为3000）
    ports:
      - "8000:8000" # frontend
      - "3000:3000" # backend
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "/srv/artipub/mongo:/data/db"
    ports:
      - "27017:27017"
```
