### ISSUE TITLE
【docker版本】后端访问问题

### ISSUE THREAD

**Issue by Ruffianjiang** [crawlab-team/artipub#34]
安装的宿主机ip：192.168.245.200
1、docker的配置文件未改变。容器内有docker-compose文件，config.js的mongo地址配置依旧是localhost，没使用宿主机的docker-compose配置
2、web页面访问不到后端服务，小助手可以，下面是助手访问的日志
```
[2019-09-24T00:38:59.792] [INFO] default - listening on port 3000
GET /platforms 304 50.753 ms - -
POST /cookies 200 212.127 ms - 15
```
web访问一下两个接口，没结果
```
http://192.168.245.200:3000/platforms
http://192.168.245.200:3000/platforms/checkCookies
```
mongo中有cookie的数据

**Comment by tikazyq** [comment]
如果您是用Docker安装的，请参考以下`docker-compose.yml`文件，注意将`ARTIPUB_API_ADDRESS更换为对应的宿主机IP+端口号（默认为3000）

```
version: '3.3'
services:
  app:
    image: "tikazyq/artipub:latest"
    environment:
      MONGO_HOST: "mongo"
      ARTIPUB_API_ADDRESS: "localhost:3000" # 后端API地址，如果安装地址不在本机，请修改为服务器IP地址+端口号（默认为3000）
    ports:
      - "8000:8000" # frontend
      - "3000:3000" # backend
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
```
