### ISSUE TITLE
docker-compose部署报连接mongodb数据库错误

### ISSUE THREAD

**Issue by JohnieXu** [crawlab-team/artipub#85]
**docker-compose部署报连接mongodb数据库错误**
错误信息如下：
```
UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
```

**Comment by JinluZhang1126** [comment]
同问，需要配置一遍MongoDB吗

**Comment by HoYor** [comment]
按理说这个127.0.0.1:27017应该是docker内部网段的地址吧，这里是准备连宿主机？

**Comment by SuperNG6** [comment]
配置写错了吧

````
version: '3.3'
services:
  app:
    image: "tikazyq/artipub:latest"
    environment:
      MONGO_HOST: "mongo"
      ARTIPUB_API_ADDRESS: "mongo:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
````
