### ISSUE TITLE
启动报错Cannot GET /

### ISSUE THREAD

**Issue by FJiayang** [crawlab-team/artipub#99]
配置文件
```yaml
version: '3.3'
services:
  app:
    image: "tikazyq/artipub:latest"
    environment:
      MONGO_HOST: "192.168.1.25"
      ARTIPUB_API_ADDRESS: "http://192.168.1.24:3000" # 后端API地址，如果安装地址不在本机，请修改为服务器IP地址+端口号（默认为3000）
      MONGO_USERNAME: "admin"
      MONGO_PASSWORD: "admin"
    ports:
      - "8000:8000" # frontend
      - "3000:3000" # backend
```

日志：
```
Attaching to artipub_app_1
app_1  | nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
app_1  |
app_1  | > backend@1.0.0 start:backend /app
app_1  | > node server.js
app_1  |
app_1  | { npm_config_save_dev: '',
...
app_1  | GET / 404 5.642 ms - 139
app_1  | GET / 404 1.339 ms - 139
```
